export const LOGIN_USER = "LOGIN_USER",
  REGISTER_USER = "REGISTER_USER",
  REGISTRATION_STATES = "SET_REGISTRATON_STATES",
  SUCCESSFUL_REGISTRATION = "SUCCESSFUL_REGISTRATION",
  FAILED_REGISTRATION = "FAILED_REGISTRATION",
  SUCCESS_LOGIN = "SUCCESS_LOGIN",
  FAILED_LOGIN = "FAILED_LOGIN";
